feat: add simplified Chinese support
rhino-linux/rhino-pkg pull request #26
Opened 2023-08-22 15:18 UTC by LuDreamst

2023-08-22 17:33 UTC, Elsie19 commented on po/zh_CN.po
> +msgstr "正在检索Pacstall..."
Use the … character instead of the triple dots.

2023-08-22 23:11 UTC, Elsie19 requested changes

2023-08-22 23:11 UTC, Elsie19 commented on po/zh_CN.po
> +msgstr "正在检索Pacstall..."
```suggestion
msgstr "正在检索Pacstall…"
```

2023-08-22 23:11 UTC, Elsie19 commented on po/zh_CN.po
> +msgstr "正在检索apt..."
```suggestion
msgstr "正在检索apt…"
```

2023-08-22 23:11 UTC, Elsie19 commented on po/zh_CN.po
> +msgstr "正在检索flatpak..."
```suggestion
msgstr "正在检索flatpak…"
```

2023-08-22 23:11 UTC, Elsie19 commented on po/zh_CN.po
> +msgstr "正在检索snap..."
```suggestion
msgstr "正在检索snap…"
```

2023-08-22 23:11 UTC, Elsie19 approved these changes

2023-08-22 23:11 UTC, merged

2023-08-23 07:51 UTC, LuDreamst commented
After receiving emails, I thought I would make revisions later in the evening when I was free. I feel sorry I left you with work I was supposed to do. (>﹏<)

2023-08-23 08:17 UTC, LuDreamst commented on po/zh_CN.po
> +msgstr "正在检索Pacstall..."
After receiving emails, I thought I would make revisions later in the evening when I was free. I feel sorry I left you with work I was supposed to do. (>﹏<)