rewrite: switch to nushell
rhino-linux/rhino-pkg pull request #38
Opened 2023-12-11 04:09 UTC by oklopfer

should have a pacstall-programs merge that adds `pacdeps=("nu-tongues-bin")` at same time this is merged as well

2023-12-11 04:21 UTC, Elsie19 requested changes

2023-12-11 04:21 UTC, Elsie19 commented on rhino-pkg
> +      let first_table =  if $desc == true {
```suggestion
      let first_table = if $desc == true {
```

2023-12-11 04:21 UTC, Elsie19 commented on rhino-pkg
> +
Delete these lines.

2023-12-11 04:21 UTC, Elsie19 commented on rhino-pkg
> +    $input_table | filter { |row|    (($row.package | into string | str downcase | str contains $downcase_prune_term) or ($row.description | into string | str downcase | str contains $downcase_prune_
```suggestion
    $input_table | filter { |row| (($row.package | into string | str downcase | str contains $downcase_prune_term) or ($row.description | into string | str downcase | str contains $downcase_prune_term)) }
```

2023-12-11 04:21 UTC, Elsie19 commented on rhino-pkg
> +        let pacstall = do { ^pacstall -S $input  } | complete
```suggestion
        let pacstall = do { ^pacstall -S $input } | complete 
```

2023-12-11 04:21 UTC, Elsie19 commented on rhino-pkg
> +        $terminal_width = ((stty size| split column " ").column2.0 | into int)
```suggestion
        $terminal_width = ((stty size | split column " ").column2.0 | into int)
```

2023-12-11 04:21 UTC, Elsie19 commented on rhino-pkg
> +    mut results =  ($apt | append $pacstall | append $flatpak | append $snap )
```suggestion
    mut results = ($apt | append $pacstall | append $flatpak | append $snap )
```

2023-12-11 04:21 UTC, Elsie19 commented on rhino-pkg
> +        translation-dir-path | translate none-matching {search: $search_term, color: "magenta" } | print
```suggestion
        translation-dir-path | translate none-matching { search: $search_term, color: "magenta" } | print
```

2023-12-11 04:21 UTC, Elsie19 commented on rhino-pkg
> +    (translation-dir-path | translate found-matching {matches: $results_len, search: $search_term, color: "magenta"} ) + "\n" | print
```suggestion
    (translation-dir-path | translate found-matching { matches: $results_len, search: $search_term, color: "magenta"} ) + "\n" | print
```

2023-12-11 04:21 UTC, Elsie19 commented on rhino-pkg
> +
```suggestion
```

2023-12-11 04:21 UTC, Elsie19 commented on rhino-pkg
> +
```suggestion
```

2023-12-11 04:21 UTC, Elsie19 commented on rhino-pkg
> +        "install" => (input (translation-dir-path| translate ask.which-install {index: $input_final_index}) | into string),
```suggestion
        "install" => (input (translation-dir-path | translate ask.which-install { index: $input_final_index }) | into string),
```

2023-12-11 04:21 UTC, Elsie19 commented on rhino-pkg
> +        "remove" => (input (translation-dir-path| translate ask.which-remove {index: $input_final_index}) | into string),
```suggestion
        "remove" => (input (translation-dir-path | translate ask.which-remove { index: $input_final_index }) | into string),
```

2023-12-11 04:21 UTC, Elsie19 commented on rhino-pkg
> +        "info" => (input (translation-dir-path |  translate ask.which-info{ index: $input_final_index }) |into string),
```suggestion
        "info" => (input (translation-dir-path |  translate ask.which-info { index: $input_final_index }) |into string),
```

2023-12-11 04:21 UTC, Elsie19 commented on rhino-pkg
> +        if ($user_input_ints |select $i).0 > $input_final_index {
```suggestion
        if ($user_input_ints | select $i).0 > $input_final_index {
```

2023-12-11 04:21 UTC, Elsie19 commented on rhino-pkg
> +    for i in 0..<($drop_list|length) {
```suggestion
    for i in 0..<($drop_list | length) {
```

2023-12-11 04:21 UTC, Elsie19 commented on rhino-pkg
> +        $user_input_ints = ($user_input_ints | drop nth ($drop_list| select $i).0)
```suggestion
        $user_input_ints = ($user_input_ints | drop nth ($drop_list | select $i).0)
```

2023-12-11 04:21 UTC, Elsie19 commented on rhino-pkg
> +        let error_msg = translation-dir-path | translate invalid.integers {number: $input_final_index}
```suggestion
        let error_msg = translation-dir-path | translate invalid.integers { number: $input_final_index }
```

2023-12-11 04:21 UTC, Elsie19 commented on rhino-pkg
> +        error make {msg: $error_msg}
```suggestion
        error make { msg: $error_msg }
```

2023-12-11 04:21 UTC, Elsie19 commented on rhino-pkg
> +            translation-dir-path | translate install-select {package: $pkg, manager: $provider, color: "magenta" } | print
```suggestion
            translation-dir-path | translate install-select { package: $pkg, manager: $provider, color: "magenta" } | print
```

2023-12-11 04:21 UTC, Elsie19 commented on rhino-pkg
> +            translation-dir-path | translate remove-select {package: $pkg, manager: $provider, color: "magenta" } | print
```suggestion
            translation-dir-path | translate remove-select { package: $pkg, manager: $provider, color: "magenta" } | print
```

2023-12-11 04:21 UTC, Elsie19 commented on rhino-pkg
> +            translation-dir-path | translate skipping {package: $pkg, manager: $provider, color: "magenta"} | print
```suggestion
            translation-dir-path | translate skipping { package: $pkg, manager: $provider, color: "magenta" } | print
```

2023-12-11 04:21 UTC, Elsie19 commented on rhino-pkg
> +    let user_input_ints =  user-package-selection $input "info"
```suggestion
    let user_input_ints = user-package-selection $input "info"
```

2023-12-11 04:21 UTC, Elsie19 commented on rhino-pkg
> +def search-cmd-no-args [ ] {
```suggestion
def search-cmd-no-args [] { 
```

2023-12-11 04:21 UTC, Elsie19 commented on rhino-pkg
> +    let error_msg = translation-dir-path | translate invalid.search-arguments {subcommand: $command}
```suggestion
    let error_msg = translation-dir-path | translate invalid.search-arguments { subcommand: $command }
```

2023-12-11 04:21 UTC, Elsie19 commented on rhino-pkg
> +    error make -u {msg: $error_msg}
```suggestion
    error make -u { msg: $error_msg }
```

2023-12-11 04:21 UTC, Elsie19 commented on rhino-pkg
> +       error make -u { msg: $error_msg}
```suggestion
       error make -u { msg: $error_msg }
```

2023-12-11 04:21 UTC, Elsie19 commented on rhino-pkg
> +        let error_msg = translation-dir-path | translate invalid.subcommand {subcommand: $rest.0}
```suggestion
        let error_msg = translation-dir-path | translate invalid.subcommand { subcommand: $rest.0 }
```

2023-12-11 04:21 UTC, Elsie19 commented on rhino-pkg
> +
Remove these.

2023-12-11 04:21 UTC, Elsie19 commented on rhino-pkg
> +
```suggestion
```

2023-12-11 05:25 UTC, oklopfer commented
Makefile will also need to be edited for the tomls

2023-12-11 05:33 UTC, oklopfer commented on rhino-pkg
> +    "/usr/src/pacstall/rhino-pkg/translation_tomls"
this is not a valid dir that will ever exist. it should be in a newly created /usr/local/share/rhino-pkg, not /usr/src/pacstall

2023-12-11 05:41 UTC, oklopfer commented on rhino-pkg
> +#      .,,:dXMK
this page lost all of its color when displaying in terminal (which is actually quite important)... can we bring it back?

2023-12-12 01:31 UTC, Elsie19 commented on rhino-pkg
> +#      .,,:dXMK
No.

2023-12-12 01:34 UTC, oklopfer commented on rhino-pkg
> +#      .,,:dXMK
Then it should be a manpage instead, without the color it’s confusing and hard to read

2023-12-12 01:40 UTC, Elsie19 commented on rhino-pkg
> +#      .,,:dXMK
Manpages can't be colored with ansi codes.

2023-12-18 02:55 UTC, Elsie19 commented
@oklopfer any updates on the changes I suggested?

2023-12-18 02:57 UTC, oklopfer commented
Yeah, you haven’t done any of them yet. It’s your project, Elsie. You maintain it. Not me.

2023-12-18 02:57 UTC, Elsie19 commented
It's your PR but fine.

2023-12-18 02:58 UTC, oklopfer commented
It’s also all @wren54 ‘s commits. I just made the PR so we could track it.

2024-11-01 16:49 UTC, Elsie19 commented
This one isn't happening, but look at https://github.com/Elsie19/rpk2

2024-11-01 16:49 UTC, closed without merging