feat: rewrite in nushell
rhino-linux/rhino-pkg pull request #52
Opened 2024-12-05 15:54 UTC by Elsie19

2024-12-31 20:52 UTC, Elsie19 commented
https://github.com/Elsie19/nu_plugin_nutext

![image](https://vignette.wikia.nocookie.net/epicrapbattlesofhistory/images/f/f2/Your_Savior_Is_Here_Loki.gif/revision/latest?cb=20180708043813)

2025-01-01 23:20 UTC, ajstrongdev commented
Issues to note whilst testing:
- Seems to hang on snapd, when `^C` is pressed this is the output:
```bash
^CError: nu::shell::column_not_found

  × Cannot find column 'Publisher'
    ╭─[/usr/share/rhino-pkg/modules/pluggables/snap.nu:19:15]
 18 │             | detect columns --guess
 19 │             | reject Publisher Version
    ·               ───┬── ────┬────
    ·                  │       ╰── cannot find column 'Publisher'
    ·                  ╰── value originates here
 20 │             | rename --column { Name: pkg }
    ╰────
```

- Requires support for `nix` and `am` package managers, as these can be enabled during `rhino-setup`

2025-01-01 23:30 UTC, Elsie19 commented
What did you search..? I need reproducible input.

2025-01-01 23:44 UTC, ajstrongdev commented
> What did you search..? I need reproducible input.

`rpk search discord`

2025-01-02 21:44 UTC, Elsie19 commented
Wait you said this was in a docker container?

2025-01-03 02:52 UTC, Elsie19 commented
We determined the issue only happens in a docker container.

2025-01-03 15:19 UTC, Elsie19 commented
## Other stuff
We will have to keep [`nushell-bin`](https://pacstall.dev/packages/nushell-bin), [`rhino-pkg-git`](https://pacstall.dev/packages/rhino-pkg-git), and [`nutext-bin`](https://pacstall.dev/packages/nutext-bin) tightly coupled, moreso `nutext-bin` and `nushell-bin`, as we will need to update `nutext-bin` for every nushell update.

2025-01-03 21:36 UTC, ajstrongdev requested changes
One issue is that the program can't detect the nutext plugin, causing an exception.
![image](https://github.com/user-attachments/assets/724dfa05-cc84-494a-89f3-50f18e2ab374)

2025-01-05 18:45 UTC, Elsie19 commented
Apparently you need to add the plugin in a nu shell before being able to run it. I will look more into it.

2025-01-06 22:19 UTC, ajstrongdev requested changes
A few issues:
- Unexpected behaviors when not giving a number as an input.
- No `rpk help` command. It seems like you copy/pasted `rpk help` output to `rpk -h`, which presents issues. Furthermore it seems like auto-generated help information displays beneath this
- Using `apt-remove` instead of `apt autoremove`
- Running `rpk` without arguments returns an error, when it should return the content of the help command.

What i mean by the first point:
- When running `rpk install discord` and I select no options, it will say "selecting discord from snap" and then... fail?
- When running `rpk remove discord` and I press enter without putting a number in, it throws an error.

Please ensure that rpk2 has consistent functionality with the first rpk.

2025-01-06 22:46 UTC, Elsie19 commented
> * Furthermore it seems like auto-generated help information displays beneath this

That cannot be turned off btw.

2025-01-06 22:50 UTC, Elsie19 commented
> A few issues:
> 
> * Unexpected behaviors when not giving a number as an input.
> * No `rpk help` command. It seems like you copy/pasted `rpk help` output to `rpk -h`, which presents issues. Furthermore it seems like auto-generated help information displays beneath this

There is no `rpk help` command. You are confusing this behavior with the catch-all flag:

https://github.com/rhino-linux/rhino-pkg/blob/0b7fc65afed6dd64b1da189adb08c27b44d977e2/rhino-pkg#L200-L203

> * Using `apt-remove` instead of `apt autoremove`

That's not a command, unless you meant `apt auto-remove`:

https://github.com/rhino-linux/rhino-pkg/blob/0b7fc65afed6dd64b1da189adb08c27b44d977e2/rhino-pkg#L284

In which case those are the same in apt.

> * Running `rpk` without arguments returns an error, when it should return the content of the help command.
> 
> What i mean by the first point:
> 
> * When running `rpk install discord` and I select no options, it will say "selecting discord from snap" and then... fail?
> * When running `rpk remove discord` and I press enter without putting a number in, it throws an error.
> 
> Please ensure that rpk2 has consistent functionality with the first rpk.

Ok.

2025-01-09 09:11 UTC, oklopfer commented
> > * Using `apt-remove` instead of `apt autoremove`
> 
> 
> 
> That's not a command, unless you meant `apt auto-remove`:
> 
> 
> 
> https://github.com/rhino-linux/rhino-pkg/blob/0b7fc65afed6dd64b1da189adb08c27b44d977e2/rhino-pkg#L284

[Took you 2 months](https://discord.com/channels/1030820921235210371/1144089131455094897/1304204446154096722) to figure out `apt-remove` isn't a command, hope it doesn't take as long to figure out that you replied to AJ's typo with a link to the old bash code that you typoed in the first place: https://github.com/rhino-linux/rhino-pkg/blob/90edb60964bc66bc85928932336d0b0c54b2d30b/modules/lib/cmd.nu#L122

Don't keep asking me to test the code if you haven't done bare minimum testing yourself. `rpk cleanup` is all you had to run. And given the link above, it is evident you haven't tested this basic functionality since at least before you even opened this PR.

2025-01-09 16:04 UTC, oklopfer requested changes

2025-01-09 16:04 UTC, oklopfer commented on modules/pluggables/apt.nu
> +        []
[Search has also been broken the entire time.](https://discord.com/channels/1030820921235210371/1144089131455094897/1304207995747700736)

2025-02-13 17:43 UTC, ajstrongdev requested changes
Firstly there is no `rpk help` command, running `rhino-pkg` will also throw an error. Running either `rhino-pkg` with no arguments OR `rhino-pkg help` should provide useful output to help the user as is the default behavior of the current `rhino-pkg` implementation.

Running rpk cleanup gives output in these weird boxes with no data contained inside of them:
![image](https://github.com/user-attachments/assets/3a839ee8-24ab-4df9-86a2-a8d371b551d7)

Information actually does get formatted into a box on `rpk remove` as well:
![image](https://github.com/user-attachments/assets/0c79fae5-2782-46fa-92e0-a9281018fd5e)

Even more urgent is the fact that there are seemingly **no** checks for whether Nala is installed on the system. I didn't find any skimming the code, nor does it check when testing. Fix this.

2025-02-15 17:59 UTC, devtracer commented
Greetings,

I am the user behind the backup and recovery ideas, which you can find here: #57 . I would be glad to continue the project and transfer those functions to this rewrite. I’d also like to contribute to the project, so I would appreciate your assistance in setting it up on my PC.

Additionally, creating an app store version of this project seems like a great idea to me. This way, we can develop and maintain Rhino Linux's app store, similar to other distributions out there—take openSUSE's YaST, for example, which I greatly admire. I can try to build a very basic beta version soon so we can start working on it. Eventually, we could offer this app store to the world under Rhino Linux's name.

Best regards,

devtracer

2025-02-16 11:05 UTC, ajstrongdev commented
> Greetings,
> 
> I am the user behind the backup and recovery ideas, which you can find here: #57 . I would be glad to continue the project and transfer those functions to this rewrite. I’d also like to contribute to the project, so I would appreciate your assistance in setting it up on my PC.
> 
> Additionally, creating an app store version of this project seems like a great idea to me. This way, we can develop and maintain Rhino Linux's app store, similar to other distributions out there—take openSUSE's YaST, for example, which I greatly admire. I can try to build a very basic beta version soon so we can start working on it. Eventually, we could offer this app store to the world under Rhino Linux's name.
> 
> Best regards,
> 
> devtracer

Hello again @devtracer

It would be great if you could port functionality into the rewrite. There is currently an ongoing discussion as to whether we continue on rewriting rhino-pkg in Nushell, or whether we pivot to an alternative such as Go or Rust. You can find and contribute to the discussion here: https://github.com/rhino-linux/tracker/issues/28

It would be best (in my opinion) to open up a separate feature proposal if you would wish to create/incorporate a graphical application store within Rhino Linux. You can do that here: https://github.com/rhino-linux/tracker

Finally, I would like to ask that you would join our Discord (if you would like to), I personally believe that you are making excellent contributions, and would love to involve you in development discussions where possible, and most of our development / discussions happen in the Rhino Linux discord server. The invite can be found here: https://discord.gg/reSvc8Ztk3

2025-02-17 21:33 UTC, Elsie19 commented
> Finally, I would like to ask that you would join our Discord (if you would like to), I personally believe that you are making excellent contributions, and would love to involve you in development discussions where possible, and most of our development / discussions happen in the Rhino Linux discord server. The invite can be found here: [discord.gg/reSvc8Ztk3](https://discord.gg/reSvc8Ztk3)

I would prefer technical discussions about rhino-pkg to be here rather than on discord.

2025-02-18 10:20 UTC, amirali-dashti commented
> Hello again @devtracer
> 
> It would be great if you could port functionality into the rewrite. There is currently an ongoing discussion as to whether we continue on rewriting rhino-pkg in Nushell, or whether we pivot to an alternative such as Go or Rust. You can find and contribute to the discussion here: [rhino-linux/tracker#28](https://github.com/rhino-linux/tracker/issues/28)
> 
> It would be best (in my opinion) to open up a separate feature proposal if you would wish to create/incorporate a graphical application store within Rhino Linux. You can do that here: https://github.com/rhino-linux/tracker
> 
> Finally, I would like to ask that you would join our Discord (if you would like to), I personally believe that you are making excellent contributions, and would love to involve you in development discussions where possible, and most of our development / discussions happen in the Rhino Linux discord server. The invite can be found here: https://discord.gg/reSvc8Ztk3

Hi @ajstrongdev,

Thank you for the update and the invite! I’d be happy to participate in the discussions and contribute further to the team. I’ll make sure to check out [rhino-linux/tracker#28](https://github.com/rhino-linux/tracker/issues/28) soon.

Regarding the graphical application store, I’ll open a separate feature proposal on the tracker to discuss it in more detail. I plan to develop the GUI app store's backend in a way that allows it to seamlessly attach and connect to the package manager. This approach will ensure a stable and seamless connection, even as the package manager undergoes frequent updates.

I’m really thrilled to hear that you’re happy with my contributions so far—I truly appreciate the feedback! Thanks again for the invite; I’ll join the Discord server soon to start discussions!

Best wishes,
@amirali-dashti

2025-02-23 18:37 UTC, ajstrongdev commented
I've tested with `pacstall` and `apt` installed in my docker image (as flatpaks and snaps will not work). This seems to have massively improved. I still need to test snap/flatpak functionality but two things to note:

- We should really include Nixpkgs and AM support. 
- If possible I would like to change the `rpk remove` output so that it does not display within a table.

2025-02-23 21:45 UTC, amirali-dashti commented
Hello,

As you're building the next generation of the package, should the GUI application also be included in this build? I was thinking of an installation window where users would be able to press the installation button alongside choosing a package manager to install with. The GUI app's backend will lead to some functions that call these codes.

Feel free to share what you think. I think users would like to try this app's beta version as well.

2025-02-23 22:29 UTC, ajstrongdev commented
> Hello,
> 
> As you're building the next generation of the package, should the GUI application also be included in this build? I was thinking of an installation window where users would be able to press the installation button alongside choosing a package manager to install with. The GUI app's backend will lead to some functions that call these codes.
> 
> Feel free to share what you think. I think users would like to try this app's beta version as well.

@amirali-dashti Hello. Please do understand that the GUI application store is currently a proposal, this rewrite is not intending to nor will support functionality for that. Furthermore I feel as though, with the GUI app store issue still "a proposal" and not an agreed upon feature, that you might be getting a bit ahead of yourself :smile:

What would be great is if someone could contribute support for the Nix and AM package managers into this rewrite, as that is where our focus should be at the moment, feel free to submit a Pull Request into the `nushell` branch.

2025-02-23 22:44 UTC, amirali-dashti commented
> @amirali-dashti Hello. Please do understand that the GUI application store is currently a proposal, this rewrite is not intending to nor will support functionality for that. Furthermore I feel as though, with the GUI app store issue still "a proposal" and not an agreed upon feature, that you might be getting a bit ahead of yourself :smile:
> 
> What would be great is if someone could contribute support for the Nix and AM package managers into this rewrite, as that is where our focus should be at the moment, feel free to submit a Pull Request into the `nushell` branch.

@ajstrongdev Thanks for the reply.  I understand, I thought a basic, early agreement would be enough to start building a template version of the proposal alongside this new project, to check if whether this project passes and gets approved or not; similar to a laboratory's research process.

I've tried Nix one, and I have to say I've liked it so far. ```nix-env -qaP <package-name>``` searches for all of the available packages. Furthermore, this scripts installs the package: ```nix-env -i <package_name>```. The other approach would be an auto editor script to edit the ```environment.systemPackages``` of ```configuration.nix```. I think you can add the nix support with copying one of those other package manager's scripts and change the commands with these, which I've mentioned here. I can do it if you want, but this's the idea I have in mind for adding Nix package manager.

2025-02-23 22:54 UTC, amirali-dashti commented
@ajstrongdev To confirm, as you've mentioned here, the GUI app will be continued once it passes the proposal stage 👍🙏

2025-02-23 23:21 UTC, oklopfer commented
just did some testing with:
```bash
pkgname="rhino-pkg-git"
source=("https://github.com/rhino-linux/rhino-pkg.git#branch=nushell")
arch=("all")
pkgver="2.0.0"
gives="rhino-pkg"
makedepends=("make")
pacdeps=("nutext-git")  
pkgdesc="Rhino-pkg wrapper script"
maintainer=("Oren Klopfer <oren@taumoda.com>")

package() {
  cd "${gives}"
  DESTDIR="${pkgdir}" make install
  mkdir -p "${pkgdir}/usr/bin"
  install -Dm755 "${gives}" "${pkgdir}/usr/bin/${gives}"
  ln -sf "/usr/bin/${gives}" "${pkgdir}/usr/bin/rpk"
}
```
overall is very good, there was a search hanging issue I experienced a while back that I still need to test, but almost everything is quite solid now. Few minor things:
1. this "are you sure" prompt is missing in the rewrite:
![image](https://github.com/user-attachments/assets/6977eba7-5e56-4da6-a068-895e786df262)
2. as is this one: 
![image](https://github.com/user-attachments/assets/a51cc740-0877-4e53-9b2c-cbcdb43c6cab)
3. this should say packages plural: <img width="588" alt="Screenshot 2025-02-23 at 6 18 16 PM" src="https://github.com/user-attachments/assets/48e41664-a974-4e7e-a6ed-6a0dfb181244" />

4. Ideally we want to figure out how to filter out pacstall packages from apt queries: <img width="1000" alt="Screenshot 2025-02-23 at 6 18 39 PM" src="https://github.com/user-attachments/assets/b09ab1e9-b73d-4c21-970b-75e662501f16" />

But again, overall great job and solid improvements. I also think it would be great if we could get the lists to spread out into multiple columns.

2025-02-24 09:56 UTC, ajstrongdev commented
> @ajstrongdev Thanks for the reply. I understand, I thought a basic, early agreement would be enough to start building a template version of the proposal alongside this new project, to check if whether this project passes and gets approved or not; similar to a laboratory's research process.
> 
> I've tried Nix, and I have to say I've liked it so far. `nix-env -qaP <package-name>` searches for all of the available packages. Furthermore, this scripts installs a particular package: `nix-env -i <package_name>`. The other approach would be an auto editor script to edit the `environment.systemPackages` of `configuration.nix`. I think you can add the nix support with copying one of those other package manager's scripts and changing the commands with these, which I've mentioned here. I can do it if you want, but this's the idea I have in mind for adding Nix package manager.

> @ajstrongdev To confirm, as you've mentioned here, the GUI app will be continued once it passes the proposal stage 👍🙏

@amirali-dashti Again, you are free to write the code for it, you are allowed to do that obviously, I just do not want to make any promises of this being merged when it is still a very early discussion, and for you to see the progress you've made as "wasted time" if we do not agree on the proposal or implementation. Many members of the team are yet to give a solid response, please do allow time for this, as we are volunteer maintainers and have our own personal lives.

> I thought a basic, early agreement would be enough to start building a template version of the proposal alongside this new project.

This is not usually how we do things. We typically agree on a proposal and initial concept before beginning development. Again, there is nothing stopping you from writing the program, but I will not make any guarantees that the implementation you design will be merged.

2025-03-04 16:53 UTC, Elsie19 commented
> 4. Ideally we want to figure out how to filter out pacstall packages from apt queries

We actually do, the issue is that we don't change the `Section` key in `-deb` packages, so we don't (based solely on the aptitude query) know about those packages, but we do accurately filter out any non-deb package.

2025-03-06 14:20 UTC, Elsie19 commented
@oklopfer @ajstrongdev rereview please.

2025-03-06 20:01 UTC, Elsie19 commented
> 3. If I select nothing it still shows the prompt:
> 
> <img alt="Screenshot 2025-03-06 at 2 12 41 PM" width="444" src="https://private-user-images.githubusercontent.com/104327997/420056960-fbf9c0c2-07e9-4f65-9b11-100f3b601751.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NDEyOTExMTgsIm5iZiI6MTc0MTI5MDgxOCwicGF0aCI6Ii8xMDQzMjc5OTcvNDIwMDU2OTYwLWZiZjljMGMyLTA3ZTktNGY2NS05YjExLTEwMGYzYjYwMTc1MS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjUwMzA2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI1MDMwNlQxOTUzMzhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02Y2YzZWI1ZGY0NmE2NGE1OGQ1NmQwMmYxM2Q4NGNjY2U0MWE0Yjc0YWQ2MjExMzhjNjhkNjdhMmViMWYxYzkzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.pIivvUKBDwKyl1V4TVXe_wuQYgGpe598qpe-Hu1l-4o">

I believe that is rpk1 behavior:

https://github.com/rhino-linux/rhino-pkg/blob/66de28f1a3bfe9a4ae8062110877a6f4bcd6e667/rhino-pkg#L387-L388

2025-03-06 22:58 UTC, oklopfer requested changes

2025-03-06 22:58 UTC, oklopfer commented on rhino-pkg
> +    }
```suggestion
    if not $yes {
        if not (input (_ "Attempting to repair dependencies and remove unused packages. Continue? ({y}/{n}) " {
                    y: $"(ansi green_bold)y(ansi reset)",
                    n: $"(ansi red_bold)N(ansi reset)"
                }
            )
                | str downcase
                | str starts-with "y") {
            exit 1
        }
    }
```

2025-03-06 22:58 UTC, oklopfer commented on rhino-pkg
> +        if ($response | is-empty) or ($response | str downcase | str starts-with "n") {
```suggestion
        if not ($response | str downcase | str starts-with "y") {
```

2025-03-06 22:58 UTC, oklopfer commented on rhino-pkg
> +        if ($response | is-empty) or ($response | str downcase | str starts-with "n") {
```suggestion
        if not ($response | str downcase | str starts-with "y") {
```

2025-03-06 22:58 UTC, oklopfer commented on rhino-pkg
> +    }
missing "are you sure" prompt

2025-03-07 19:47 UTC, oklopfer commented
> > 4. Ideally we want to figure out how to filter out pacstall packages from apt queries
> 
> We actually do, the issue is that we don't change the `Section` key in `-deb` packages, so we don't (based solely on the aptitude query) know about those packages, but we do accurately filter out any non-deb package.

We require deb packages to put the actual package name in `gives` always, so can't we just parse out any `_gives` results from `/var/lib/pacstall/metadata/*-deb` in addition?

2025-03-07 20:18 UTC, oklopfer commented
> > > 4. Ideally we want to figure out how to filter out pacstall packages from apt queries
> > 
> > 
> > We actually do, the issue is that we don't change the `Section` key in `-deb` packages, so we don't (based solely on the aptitude query) know about those packages, but we do accurately filter out any non-deb package.
> 
> We require deb packages to put the actual package name in `gives` always, so can't we just parse out any `_gives` results from `/var/lib/pacstall/metadata/*-deb` in addition?

Also importantly actually, pacstall packages should be parsing their pacstall versions from metadata, not their apt versions:

<img width="621" alt="Screenshot 2025-03-07 at 3 00 03 PM" src="https://github.com/user-attachments/assets/76c896fe-1ea5-4945-9eb3-316986a19586" />


This may actually be something we have to fix in Pacstall, as `-Ci` parses from dpkg instead of metadata, leading to mismatches:

<img width="621" alt="Screenshot 2025-03-07 at 3 00 03 PM" src="https://github.com/user-attachments/assets/3612182c-d5cf-4d30-a7b8-9d4e86f27935" />

This is a bit of a convoluted issue though, because we use this query on other places:
<img width="995" alt="Screenshot 2025-03-07 at 3 08 56 PM" src="https://github.com/user-attachments/assets/f117d28a-66cb-43b1-b27f-09ec0d9e0162" />

1. For `-Ci`, I think we can keep `-Ci version` as is, but perhaps we can add a `-Ci pkgver` option which reads from the already provided `${_version}` variable in metadata instead of from dpkg, giving the pacstall version instead of the apt version.

2. For the reinstall warning, we should just simply be parsing `-Ci pkgver` instead of dpkg, since the pacstall version is the one that matters if pacstall is performing a reinstall.

3. For the version constraints, it should probably be left untouched (keep it using the apt/dpkg version), since thats the actual version that `dpkg`/`aptitude` will be checking on constraints.

2025-03-13 17:25 UTC, oklopfer requested changes

2025-03-13 17:25 UTC, oklopfer commented on modules/pluggables/pacstall.nu
> +                    "version": (^pacstall -Ci $pkg version)
```suggestion
                    "version": (^pacstall -Ci $pkg pacversion)
```

2025-03-14 14:20 UTC, ajstrongdev requested changes
Was testing with this pacscript on a rhino install (not docker):
```
pkgname="rhino-pkg-git"
source=("https://github.com/rhino-linux/rhino-pkg.git#branch=nushell")
arch=("all")
pkgver="2.0.0"
gives="rhino-pkg"
makedepends=("make")
pacdeps=("nutext-git")  
pkgdesc="Rhino-pkg wrapper script"
maintainer=("Oren Klopfer <oren@taumoda.com>")

package() {
  cd "${gives}"
  DESTDIR="${pkgdir}" make install
  mkdir -p "${pkgdir}/usr/bin"
  install -Dm755 "${gives}" "${pkgdir}/usr/bin/${gives}"
  ln -sf "/usr/bin/${gives}" "${pkgdir}/usr/bin/rpk"
```
and got:
```
[~] aj@rhino $ rpk remove htop
Searching apt…
Searching snap…
No snaps are installed yet. Try 'snap install hello-world'.
Error: nu::shell::pipeline_mismatch

  × Pipeline empty.
   ╭─[/usr/share/rhino-pkg/modules/pluggables/snap.nu:7:15]
 6 │             | detect columns
 7 │             | reject Rev Tracking Publisher Notes
   ·               ───┬──
   ·                  ╰── no input value was piped in
 8 │             | rename --column { Name: pkg }
   ╰────
```
I have snap installed, but no snaps. You need to add handling for this.

2025-03-30 20:40 UTC, ajstrongdev commented
Myself and @oklopfer will test in the coming week. If both of us approve it we will bump rhino-pkg 2.0.0 into Rhino Linux

2025-04-15 16:55 UTC, ajstrongdev requested changes
```
[~] aj@rhino $ rpk install hello-rhino
Searching apt…
Searching snap…
No matching snaps for "hello-rhino"
Error: nu::shell::only_supports_this_input_type

  × Input type not supported.
    ╭─[/usr/share/rhino-pkg/modules/pluggables/snap.nu:17:10]
 16 │     if (exists "snap") {
 17 │         ^snap search $input
    ·          ──┬─
    ·            ╰── input type: nothing
 18 │             | detect columns --guess
 19 │             | reject Publisher Version
    ·               ───┬──
    ·                  ╰── only record, table, and list<any> input data is supported
 20 │             | rename --column { Name: pkg }
    ╰────
```

Using a hyphen character while querying for packages causes it to fault. Fix this.

2025-05-20 04:48 UTC, ajstrongdev approved these changes
Tested all commands and available package managers, no issues came up in my testing. Happy to approve :fire: 

@oklopfer you should review as well before we merge but all is fine from my end :+1:

2025-06-13 16:32 UTC, oklopfer commented
it is time

2025-06-13 16:32 UTC, merged